// let productsData = [
//   {
//     id: 1,
//     featureType: 'Бестселлер',
//     discount: '-50%',
//     imgLink: '/assets/img/goods-image/parfume.png',
//     cardName: 'Какие-то духи с каким-то возможно вкусным запахом. id: 1,',
//     goodsSize: '235 мл.',
//     finalPrice: '5000 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'bestsellers',
//   },
//   {
//     id: 2,
//     featureType: 'Бестселлер',
//     discount: '-70%',
//     imgLink: '/assets/img/goods-image/parfume.png',
//     cardName: 'Какие-то духи с каким-то возможно вкусным запахом.id: 2,',
//     goodsSize: '235 мл.',
//     finalPrice: '5000 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'bestsellers',
//   },
//   {
//     id: 3,
//     featureType: 'Бестселлер',
//     discount: '-50%',
//     imgLink: '/assets/img/goods-image/parfume.png',
//     cardName: 'Какие-то духи с каким-то возможно вкусным запахом.id: 3,',
//     goodsSize: '235 мл.',
//     finalPrice: '5000 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'bestsellers',
//   },
//   {
//     id: 4,
//     featureType: 'Бестселлер',
//     discount: '-50%',
//     imgLink: '/assets/img/goods-image/parfume.png',
//     cardName: 'Какие-то духи с каким-то возможно вкусным запахом.id: 4,',
//     goodsSize: '235 мл.',
//     finalPrice: '5000 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'bestsellers',
//   },
//   {
//     id: 5,
//     featureType: 'Бестселлер',
//     discount: '-50%',
//     imgLink: '/assets/img/goods-image/parfume.png',
//     cardName: 'Какие-то духи с каким-то возможно вкусным запахом.id: 5,',
//     goodsSize: '235 мл.',
//     finalPrice: '5000 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'bestsellers',
//   },
//   {
//     id: 6,
//     featureType: 'Новинки',
//     discount: '-25%',
//     imgLink: '/assets/img/goods-image/cream.png',
//     cardName:
//       'Дневной Уход от Морщин & для Плотности Кожи - Все типы кожи id: 6,',
//     goodsSize: '235 мл.',
//     finalPrice: '7500 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'novelties',
//   },
//   {
//     id: 7,
//     featureType: 'Новинки',
//     discount: '-25%',
//     imgLink: '/assets/img/goods-image/cream.png',
//     cardName:
//       'Дневной Уход от Морщин & для Плотности Кожи - Все типы кожи id: 7,',
//     goodsSize: '235 мл.',
//     finalPrice: '7500 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'novelties',
//   },
//   {
//     id: 8,
//     featureType: 'Новинки',
//     discount: '-25%',
//     imgLink: '/assets/img/goods-image/cream.png',
//     cardName:
//       'Дневной Уход от Морщин & для Плотности Кожи - Все типы кожи id: 8,',
//     goodsSize: '235 мл.',
//     finalPrice: '7500 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'novelties',
//   },
//   {
//     id: 9,
//     featureType: 'Новинки',
//     discount: '-25%',
//     imgLink: '/assets/img/goods-image/cream.png',
//     cardName:
//       'Дневной Уход от Морщин & для Плотности Кожи - Все типы кожи id: 9,',
//     goodsSize: '235 мл.',
//     finalPrice: '7500 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'novelties',
//   },
//   {
//     id: 10,
//     featureType: 'Новинки',
//     discount: '-25%',
//     imgLink: '/assets/img/goods-image/cream.png',
//     cardName:
//       'Дневной Уход от Морщин & для Плотности Кожи - Все типы кожи id: 10,',
//     goodsSize: '235 мл.',
//     finalPrice: '7500 ',
//     priceWithoutDiscount: '10000 ',
//     productCategory: 'novelties',
//   },
//   {
//     id: 11,
//     featureType: '',
//     discount: '-99%',
//     imgLink: '/assets/img/goods-image/parfume-2.png',
//     cardName:
//       'Мицеллярная Вода для Снятия Макияжа 2 в 1 с Микроводорослями, 400 мл id: 11,',
//     goodsSize: '235 мл.',
//     finalPrice: '1000 ',
//     priceWithoutDiscount: '100000 ',
//     productCategory: 'customerChoise',
//   },
//   {
//     id: 12,
//     featureType: '',
//     discount: '-99%',
//     imgLink: '/assets/img/goods-image/parfume-2.png',
//     cardName:
//       'Мицеллярная Вода для Снятия Макияжа 2 в 1 с Микроводорослями, 400 мл id: 12,',
//     goodsSize: '235 мл.',
//     finalPrice: '1000 ',
//     priceWithoutDiscount: '100000 ',
//     productCategory: 'customerChoise',
//   },
//   {
//     id: 13,
//     featureType: '',
//     discount: '-99%',
//     imgLink: '/assets/img/goods-image/parfume-2.png',
//     cardName:
//       'Мицеллярная Вода для Снятия Макияжа 2 в 1 с Микроводорослями, 400 мл id: 13,',
//     goodsSize: '235 мл.',
//     finalPrice: '1000 ',
//     priceWithoutDiscount: '100000 ',
//     productCategory: 'customerChoise',
//   },
//   {
//     id: 14,
//     featureType: '',
//     discount: '-99%',
//     imgLink: '/assets/img/goods-image/parfume-2.png',
//     cardName:
//       'Мицеллярная Вода для Снятия Макияжа 2 в 1 с Микроводорослями, 400 мл id: 14,',
//     goodsSize: '235 мл.',
//     finalPrice: '1000 ',
//     priceWithoutDiscount: '100000 ',
//     productCategory: 'customerChoise',
//   },
//   {
//     id: 15,
//     featureType: '',
//     discount: '-99%',
//     imgLink: '/assets/img/goods-image/parfume-2.png',
//     cardName:
//       'Мицеллярная Вода для Снятия Макияжа 2 в 1 с Микроводорослями, 400 мл id: 15,',
//     goodsSize: '235 мл.',
//     finalPrice: '1000 ',
//     priceWithoutDiscount: '100000 ',
//     productCategory: 'customerChoise',
//   },
// ];

// let newArr = productsData.filter(i => i.productCategory === 'bestsellers');

// console.log(newArr);
